name: sqlite_viewer
version: 0.0.1+4
homepage: http://www.icodeforyou.com
publish_to: 'none'

environment:
  sdk: ">=2.16.1 <3.0.0" #Dart SDK 2022-02-18
  flutter: ">=2.10.2"

dependencies:
  cupertino_icons: ^1.0.4
  drift: ^1.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^4.4.1
  hive_flutter: ^1.1.0
  persisted_cache:
    git:
      url: https://github.com/RAE-Health/persisted_cache.git
  path_provider: ^2.0.7
  sqlite3_flutter_libs: ^0.5.3
  sqflite: ^2.0.2

dependency_overrides:
  extensions_package:
    git:
      url: https://github.com/RAE-Health/extensions_package.git

dev_dependencies:
  flutter_lints: ^1.0.4
  build_runner:
  test:
  drift_dev: ^1.0.2

flutter:
  uses-material-design: true
  generate: false
